### ISSUE TITLE
Yazilar anlasilan olsun

### ISSUE THREAD

**Issue by samirkarimov** [H-Punhan/PragmatechFoundationProject#1]
https://github.com/H-Punhan/PragmatechFoundationProject/blob/e8eee3e1b9790e9d480b6ccd8f019fe6fc15a04c/exercise/index.html#L66

bu yazilarin yerine lorem ipsum yazisini elave edebilersen

**Comment by H-Punhan** [comment]
Yazilar Elave olundu

**Comment by H-Punhan** [comment]
Yazilar elave olundu
