### ISSUE TITLE
Funksiyada parametr --> arqument məntiqi tətbiq olunmalıdı

### ISSUE THREAD

**Issue by Sevil2005** [H-Punhan/PragmatechFoundationProject#4]
https://github.com/H-Punhan/PragmatechFoundationProject/blob/ea0219e10ffd24220a0bc7c9c18b570d8721da98/tap%C5%9F%C4%B1r%C4%B1qlar/Python%20task/index.py#L4
yazdığınız bütün funksiyalarda list üçün parametr təyin edib, mylist dəyişənini argument olaraq gondersez daha praktik və düzgün yol olar.
https://github.com/H-Punhan/PragmatechFoundationProject/blob/ea0219e10ffd24220a0bc7c9c18b570d8721da98/tap%C5%9F%C4%B1r%C4%B1qlar/Python%20task/index.py#L31
məsələn burda funksiya xaricindəki mylist dəyişənini onun içində global dəyişən kimi təyin edib üzərində əməliyyat aparmanız funksiya məntiqini pozur. ona görə funksiyaya parametrlər təyin etməniz lazımdı

**Comment by H-Punhan** [comment]
Butun funksiyalar ucun parametr elave olundu
