### ISSUE TITLE
Algoritm məntiqində gördüyüm yanlışlar

### ISSUE THREAD

**Issue by Sevil2005** [H-Punhan/PragmatechFoundationProject#5]
1)
https://github.com/H-Punhan/PragmatechFoundationProject/blob/ea0219e10ffd24220a0bc7c9c18b570d8721da98/tap%C5%9F%C4%B1r%C4%B1qlar/Python%20task/index.py#L35
Burda əgər m və m-1-ci indekslərə baxmısınızsa gərək m 1-dən başlasın və bu halda
https://github.com/H-Punhan/PragmatechFoundationProject/blob/ea0219e10ffd24220a0bc7c9c18b570d8721da98/tap%C5%9F%C4%B1r%C4%B1qlar/Python%20task/index.py#L34
for loopunda start nöqtəmiz 1, son nöqtə len(mylist) olmalıdı.
2)
https://github.com/H-Punhan/PragmatechFoundationProject/blob/ea0219e10ffd24220a0bc7c9c18b570d8721da98/tap%C5%9F%C4%B1r%C4%B1qlar/Python%20task/index.py#L16
Tapşırıqda listin cüt indekslərində duran ədədləri çap etməmizi istəyir
3)
https://github.com/H-Punhan/PragmatechFoundationProject/blob/ea0219e10ffd24220a0bc7c9c18b570d8721da98/tap%C5%9F%C4%B1r%C4%B1qlar/Python%20task/index.py#L46
tapşırıqda sadəcə alınan listi çap etməmizi istədiyindən elementlərini for loop-una salmağa ehtiyac yoxdu. Həmçinin 7ci sualda da sadəcə alınan listi çap etmək kifayətdi

**Comment by H-Punhan** [comment]
Butun sefler duzeldildi
