### ISSUE TITLE
List Suallarında 5ci taskla bağlı issue

### ISSUE THREAD

**Issue by Sevil2005** [H-Punhan/PragmatechFoundationProject#6]
https://github.com/H-Punhan/PragmatechFoundationProject/blob/e069b93d21328bc3cc0463a748a51e2666a3b24b/tap%C5%9F%C4%B1r%C4%B1qlar/Python%20task/index.py#L35
5ci sualda məsələyə daha dəqiq yanaşmanız lazımdı. Mütləq deyil ki, listdəki duplicate olunmuş elementlər ardıcıl indekslərdə olsun. Ola bilər ki, 1ci və 6cı indekslərdəki elementlər bir birinə bərabər olsun. Bu hal da nəzərə alınmalıdı.

**Comment by H-Punhan** [comment]
Yerine yetirildi
